list: $/tecnotrade/websync/models/additionalpropsfields/columns.yaml
modelClass: Tecnotrade\Websync\Models\AdditionalPropsFields
title: AdditionalPropsFieldsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/additionalpropsfieldscontroller/update/:id'
