list: $/tecnotrade/websync/models/supportbrandtable/columns.yaml
modelClass: Tecnotrade\Websync\Models\SupportBrandTable
title: SupportBrandTableController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/supportbrandtablecontroller/update/:id'
