list: $/tecnotrade/websync/models/clientbrandfields/columns.yaml
modelClass: Tecnotrade\Websync\Models\ClientBrandFields
title: ClientBrandFieldsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/clientbrandfieldscontroller/update/:id'
