list: $/tecnotrade/websync/models/categorypropertygroup/columns.yaml
modelClass: Tecnotrade\Websync\Models\CategoryPropertyGroup
title: CategoryPropertyGroupController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/categorypropertygroupcontroller/update/:id'
