list: $/tecnotrade/websync/models/clientfields/columns.yaml
modelClass: Tecnotrade\Websync\Models\ClientFields
title: ClientFieldsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/clientfieldscontroller/update/:id'
