list: $/tecnotrade/websync/models/clientproductfields/columns.yaml
modelClass: Tecnotrade\Websync\Models\ClientProductFields
title: ClientProductFieldsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/clientproductfieldscontroller/update/:id'
