list: $/tecnotrade/websync/models/clientcategoryfields/columns.yaml
modelClass: Tecnotrade\Websync\Models\ClientCategoryFields
title: ClientCategoryFieldsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/clientcategoryfieldscontroller/update/:id'
