list: $/tecnotrade/websync/models/clientcategoryrules/columns.yaml
modelClass: Tecnotrade\Websync\Models\ClientCategoryRules
title: ClientCategoryRulesController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/clientcategoryrulescontroller/update/:id'
