clientcategoryfields:
    label: 'Aggiungi campo'
    view:
        list: $/tecnotrade/websync/models/clientcategoryfields/columns.yaml
        toolbarButtons: add|remove|create|delete
    manage:
        form: $/tecnotrade/websync/models/clientcategoryfields/fields.yaml
        recordsPerPage: 10
        showSearch: true