list: $/tecnotrade/websync/models/clientproprules/columns.yaml
modelClass: Tecnotrade\Websync\Models\ClientPropRules
title: ClientPropRulesController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/clientproprulescontroller/update/:id'
