plugin:
    name: 'Tecnotrade WebSync'
    description: 'Web Sync Con Plugin Mall'
    author: Tecnotrade
    icon: oc-icon-adjust
    homepage: ''
navigation:
    main-menu-item:
        label: 'tecnotrade.websync::lang.plugin.name'
        url: /
        icon: icon-life-ring
        sideMenu:
            side-menu-item2:
                label: 'Tipi Campi'
                url: tecnotrade/websync/fieldtypecontroller
                icon: icon-sitemap
            side-menu-item:
                label: 'Campi Sorgente Prodotti'
                url: tecnotrade/websync/clientproductfieldscontroller
                icon: icon-sitemap
            side-menu-item3:
                label: 'Regole Campi Sorgente Prodotti'
                url: tecnotrade/websync/clientproductrulescontroller
                icon: icon-sitemap
            side-menu-item4:
                label: 'Campi Sorgente Categorie'
                url: tecnotrade/websync/clientcategoryfieldscontroller
                icon: icon-sitemap
            side-menu-item5:
                label: 'Regole Campi Sorgente Categorie'
                url: tecnotrade/websync/clientcategoryrulescontroller
                icon: icon-sitemap
            side-menu-item6:
                label: 'Campi Sorgente Brand'
                url: tecnotrade/websync/clientbrandfieldscontroller
                icon: icon-sitemap
            side-menu-item7:
                label: 'Regole Campi Sorgente Brand'
                url: tecnotrade/websync/clientbrandrulescontroller/
                icon: icon-sitemap
            side-menu-item8:
                label: 'Campi Sorgente Proprietà Addizionali'
                url: tecnotrade/websync/additionalpropsfieldscontroller
                icon: icon-sitemap
            side-menu-item9:
                label: 'Regole Proprietà Addizionali'
                url: tecnotrade/websync/additionalpropsrulescontoller
                icon: icon-sitemap
            side-menu-item10:
                label: 'Campi Sorgente Property Groups'
                url: tecnotrade/websync/clientgrouppropfieldscontroller
                icon: icon-sitemap
            side-menu-item11:
                label: 'Regole Campi Sorgente Property Groups'
                url: tecnotrade/websync/clientgroupproprulescontroller
                icon: icon-sitemap
            side-menu-item12:
                label: 'Campi Sorgente Proprietà'
                url: tecnotrade/websync/clientpropfieldscontroller
                icon: icon-sitemap
            side-menu-item13:
                label: 'Regole Campi Sorgente Proprietà'
                url: tecnotrade/websync/clientproprulescontroller
                icon: icon-sitemap
            side-menu-item14:
                label: 'Campi Sorgente Valore Proprietà'
                url: tecnotrade/websync/clientpropvaluesfieldscontroller
                icon: icon-sitemap
            side-menu-item15:
                label: 'Regole Campi Sorgente Valore Proprietà'
                url: tecnotrade/websync/clientpropvaluerulescontroller
                icon: icon-sitemap
    main-menu-item2:
        label: 'WebSync Binding'
        url: /
        icon: icon-life-ring
        sideMenu:
            side-menu-item:
                label: 'Product Table Fields'
                url: tecnotrade/websync/tableproductfieldscontroller
                icon: icon-sitemap
            side-menu-item2:
                label: 'Brand Table Fields'
                url: tecnotrade/websync/tablebrandfieldscontroller
                icon: icon-sitemap
            side-menu-item3:
                label: 'Category Table Fields'
                url: tecnotrade/websync/tablecategoryfieldscontroller
                icon: icon-sitemap
            side-menu-item4:
                label: 'Table Product Additional Properties'
                url: tecnotrade/websync/tableadditionalpropscontroller
                icon: icon-sitemap
            side-menu-item5:
                label: 'Property Groups Table'
                url: tecnotrade/websync/tablepropertygroupscontroller
                icon: icon-sitemap
            side-menu-item6:
                label: 'Property table'
                url: tecnotrade/websync/tablepropertyfieldscontroller
                icon: icon-sitemap
            side-menu-item7:
                label: 'Property Values'
                url: tecnotrade/websync/tablepropertyvaluescontroller
                icon: icon-sitemap
    main-menu-item3:
        label: 'WebSync Support Tables'
        url: /
        icon: icon-life-ring
        sideMenu:
            side-menu-item:
                label: 'Support Product Table'
                url: tecnotrade/websync/supportproducttablecontroller
                icon: icon-sitemap
            side-menu-item2:
                label: 'Support Category Table'
                url: tecnotrade/websync/supportcategorytablecontroller
                icon: icon-sitemap
            side-menu-item3:
                label: 'Support Brand Table'
                url: tecnotrade/websync/supportbrandtablecontroller
                icon: icon-sitemap
            side-menu-item4:
                label: 'Support Additional Properties'
                url: tecnotrade/websync/supportadditionalpropscontroller
                icon: icon-sitemap
            side-menu-item5:
                label: 'Support Property Groups'
                url: tecnotrade/websync/supportpropertygroupscontroller
                icon: icon-sitemap
            side-menu-item6:
                label: 'Support Properties'
                url: tecnotrade/websync/supportpropertiescontroller
                icon: icon-sitemap
            side-menu-item7:
                label: 'Support Property Property Groups'
                url: tecnotrade/websync/supportpropertypropertygroupcontroller
                icon: icon-sitemap
            side-menu-item8:
                label: 'Category Property Group Table'
                url: tecnotrade/websync/categorypropertygroupcontroller
                icon: icon-sitemap
            side-menu-item9:
                label: 'Support Property Values'
                url: tecnotrade/websync/supportpropertyvaluescontroller
                icon: icon-sitemap
