plugin:
    name: 'Tecnotrade WebSync'
    description: 'Web Sync Con Plugin Mall'
    author: Tecnotrade
    icon: oc-icon-adjust
    homepage: ''
navigation:
    main-menu-item:
        label: 'tecnotrade.websync::lang.plugin.name'
        url: /
        icon: icon-life-ring
        sideMenu:
            side-menu-item2:
                label: 'Tipi Campi'
                url: tecnotrade/websync/fieldtypecontroller
                icon: icon-sitemap
            side-menu-item:
                label: 'Campi Sorgente Prodotti'
                url: tecnotrade/websync/clientproductfieldscontroller
                icon: icon-sitemap
            side-menu-item3:
                label: 'Regole Campi Sorgente Prodotti'
                url: tecnotrade/websync/clientproductrulescontroller
                icon: icon-sitemap
            side-menu-item4:
                label: 'Campi Sorgente Categorie'
                url: tecnotrade/websync/clientcategoryfieldscontroller
                icon: icon-sitemap
            side-menu-item5:
                label: 'Regole Campi Sorgente Categorie'
                url: tecnotrade/websync/clientcategoryrulescontroller
                icon: icon-sitemap
            side-menu-item6:
                label: 'Campi Sorgente Brand'
                url: tecnotrade/websync/clientbrandfieldscontroller
                icon: icon-sitemap
            side-menu-item7:
                label: 'Regole Campi Sorgente Brand'
                url: tecnotrade/websync/clientbrandrulescontroller/
                icon: icon-sitemap
            side-menu-item8:
                label: 'Campi Sorgente Proprietà Addizionali'
                url: tecnotrade/websync/additionalpropsfieldscontroller
                icon: icon-sitemap
            side-menu-item9:
                label: 'Regole Proprietà Addizionali'
                url: tecnotrade/websync/additionalpropsrulescontoller
                icon: icon-sitemap
    main-menu-item2:
        label: 'WebSync Binding'
        url: /
        icon: icon-life-ring
        sideMenu:
            side-menu-item:
                label: 'Product Table Fields'
                url: tecnotrade/websync/tableproductfieldscontroller
                icon: icon-sitemap
            side-menu-item2:
                label: 'Brand Table Fields'
                url: tecnotrade/websync/tablebrandfieldscontroller
                icon: icon-sitemap
            side-menu-item3:
                label: 'Category Table Fields'
                url: tecnotrade/websync/tablecategoryfieldscontroller
                icon: icon-sitemap
            side-menu-item4:
                label: 'Table Product Additional Properties'
                url: tecnotrade/websync/tableadditionalpropscontroller
                icon: icon-sitemap
    main-menu-item3:
        label: 'WebSync Support Tables'
        url: /
        icon: icon-life-ring
        sideMenu:
            side-menu-item:
                label: 'Support Product Table'
                url: tecnotrade/websync/supportproducttablecontroller
                icon: icon-sitemap
            side-menu-item2:
                label: 'Support Category Table'
                url: tecnotrade/websync/supportcategorytablecontroller
                icon: icon-sitemap
            side-menu-item3:
                label: 'Support Brand Table'
                url: tecnotrade/websync/supportbrandtablecontroller
                icon: icon-sitemap
            side-menu-item4:
                label: 'Support Additional Properties'
                url: tecnotrade/websync/supportadditionalpropscontroller
                icon: icon-sitemap
