list: $/tecnotrade/websync/models/tablecategoryfields/columns.yaml
modelClass: Tecnotrade\Websync\Models\TableCategoryFields
title: TableCategoryFieldsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/tablecategoryfieldscontroller/update/:id'
