list: $/tecnotrade/websync/models/clientgrouppropfields/columns.yaml
modelClass: Tecnotrade\Websync\Models\ClientGroupPropFields
title: ClientGroupPropFieldsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/clientgrouppropfieldscontroller/update/:id'
