list: $/tecnotrade/websync/models/tablebrandfields/columns.yaml
modelClass: Tecnotrade\Websync\Models\TableBrandFields
title: TableBrandFieldsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/tablebrandfieldscontroller/update/:id'
