list: $/tecnotrade/websync/models/supportpropertygroups/columns.yaml
modelClass: Tecnotrade\Websync\Models\SupportPropertyGroups
title: SupportPropertyGroupsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/supportpropertygroupscontroller/update/:id'
