list: $/tecnotrade/websync/models/clientpropvaluesfields/columns.yaml
modelClass: Tecnotrade\Websync\Models\ClientPropValuesFields
title: ClientPropValuesFieldsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/clientpropvaluesfieldscontroller/update/:id'
