list: $/tecnotrade/websync/models/clientgroupproprules/columns.yaml
modelClass: Tecnotrade\Websync\Models\ClientGroupPropRules
title: ClientGroupPropRulesController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/clientgroupproprulescontroller/update/:id'
