list: $/tecnotrade/websync/models/tablepropertyfields/columns.yaml
modelClass: Tecnotrade\Websync\Models\TablePropertyFields
title: TablePropertyFieldsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/tablepropertyfieldscontroller/update/:id'
