list: $/tecnotrade/websync/models/fieldtype/columns.yaml
modelClass: Tecnotrade\Websync\Models\FieldType
title: FieldTypeController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/fieldtypecontroller/update/:id'
