list: $/tecnotrade/websync/models/tableadditionalprops/columns.yaml
modelClass: Tecnotrade\Websync\Models\TableAdditionalProps
title: TableAdditionalPropsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/tableadditionalpropscontroller/update/:id'
