list: $/tecnotrade/websync/models/supportpropertypropertygroup/columns.yaml
modelClass: Tecnotrade\Websync\Models\SupportPropertyPropertyGroup
title: SupportPropertyPropertyGroupController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/supportpropertypropertygroupcontroller/update/:id'
