list: $/tecnotrade/websync/models/supportcategorytable/columns.yaml
modelClass: Tecnotrade\Websync\Models\SupportCategoryTable
title: SupportCategorytableController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/supportcategorytablecontroller/update/:id'
