list: $/tecnotrade/websync/models/clientproductrules/columns.yaml
modelClass: Tecnotrade\Websync\Models\ClientProductRules
title: ClientProductRulesController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/clientproductrulescontroller/update/:id'
