list: $/tecnotrade/websync/models/supportpropertyvalues/columns.yaml
modelClass: Tecnotrade\Websync\Models\SupportPropertyValues
title: SupportPropertyValuesController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/supportpropertyvaluescontroller/update/:id'
