list: $/tecnotrade/websync/models/tablepropertyvalues/columns.yaml
modelClass: Tecnotrade\Websync\Models\TablePropertyValues
title: TablePropertyValuesController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/websync/tablepropertyvaluescontroller/update/:id'
